name: lint elixir code base
description: lint elixir code base
inputs:
  mix_env:
    description: "mix environment to use"
    required: true
runs:
  using: "composite"
  steps:
    # install os deps
    - uses: ./.github/workflows/subtasks/os_dependencies

    # install erlang/elixir/protobuf
    - uses: ./.github/workflows/subtasks/elixir_setup

    # setup build cache
    - uses: ./.github/workflows/subtasks/cache
      with:
        os: ${{ runner.os }}
        mix_env: ${{ inputs.mix_env }}
        paths: |
          ${{ github.workspace }}/deps
          ${{ github.workspace }}/_build

    # setup plt cache
    - uses: ./.github/workflows/subtasks/cache
      with:
        os: ${{ runner.os }}
        mix_env: ${{ inputs.mix_env }}
        paths: |
          ${{ github.workspace }}/plts

    # run mix credo
    - name: "credo"
      shell: bash
      run: MIX_ENV=${{inputs.mix_env}} mix credo

    # check formatting
    - name: "credo"
      shell: bash
      run: MIX_ENV=${{inputs.mix_env}} mix format --check-formatted

    # dialyzer
    - name: "credo"
      shell: bash
      run: MIX_ENV=${{inputs.mix_env}} mix dialyzer --format github

    # whitespace check
    - name: "credo"
      shell: bash
      run: git diff-tree --check 4b825dc642cb6eb9a060e54bf8d69288fbee4904 HEAD
